name: Upload WignerSymbol

on:
  push:
    branches: [master]
  # release:
  #   types: [published]

jobs:
  deploy:
    name: Upload WignerSymbol
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    environment:
      name: pypi
      url: https://pypi.org/project/WignerSymbol
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine cibuildwheel pybind11
      - name: Build package
        run: |
          python -m build --sdist
          python -m cibuildwheel --output-dir sdist
      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: wheelhouse/*.whl
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
