name: Upload WignerSymbol

on:
  push:
    # branches: [master]
    tags: ['v*']

jobs:
  deploy:
    name: Upload WignerSymbol
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    environment:
      name: pypi
      url: https://pypi.org/project/WignerSymbol
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine cibuildwheel pybind11
      - name: Build package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          python -m build --sdist
          python -m cibuildwheel --output-dir dist
      # - uses: actions/upload-artifact@v3
      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
      #   with:
      #     path: dist/*
      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
      #   with:
      #     files: dist/*
      - name: Publish package
        # uses: pypa/gh-action-pypi-publish@release/v1
        run: |
          python -m twine upload --repository-url https://pypi.org/project/WignerSymbol dist/*
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
