name: Upload WignerSymbol

on:
  push:
    branches: [master]
  # release:
  #   types: [published]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    enviroment:
      name: pypi
      url: https://pypi.org/project/WignerSymbol
    steps:
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
