name: Upload WignerSymbol

on:
  push:
    branches: [master]
  # release:
  #   types: [published]

jobs:
  deploy:
    name: Upload WignerSymbol
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    environment:
      name: pypi
      url: https://pypi.org/project/WignerSymbol
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine wheel pybind11
      - name: Publish package
        # uses: pypa/gh-action-pypi-publish@release/v1
        run: |
          python -m build -w
          python -m twine upload dist/* --repository-url https://pypi.org/project/WignerSymbol
